### ISSUE TITLE
Corpus finder and downloader

### ISSUE THREAD

**Issue by XapaJIaMnu** [jelmervdl/empty-train#6]
We should include a GUI that helps download corpora automatically. We can mostly take the downloaders from here: https://github.com/mozilla/firefox-translations-training/tree/main/pipeline/data/importers/corpus but they need a few fixes (the opus and flores ones don't deal well with secondary language tags such as `zh_tw`.

The same is valid for the corpora finder script: https://github.com/mozilla/firefox-translations-training/blob/main/utils/find-corpus.py which I can start improving.

Not exactly sure how this would look in the GUI. Maybe a popup/ or a separate tag?

**Comment by jelmervdl** [comment]
For now I'd implement it as a separate page. I'm still having this idea of a large table in my head, where you can add a new corpus as a new row, and there are buttons to set up the filtering on each of these rows. The UI for finding adding a new row can be yet another page. If we later want to make it a popup anyway, that will be really easy. But making it a separate page gives you browser back button functionality, linking, etc. all for free.

I kind of made a mistake in having the filter editing page be able to switch between datasets. It just complicates things, but you'd never need the filtering data for different datasets at the same moment there. I might change that sooner rather than later to be table page + filter edit page for a specific dataset.
